###############################################################################
# Site settings
###############################################################################
name: Yuxuan Hou
title: Yuxuan Hou
email: yuxuanhou@zju.edu.cn
description: > # this means to ignore newlines until "url:"
  Personal website for Yuxuan Hou.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url: https://hhyxx.github.io
baseurl:   # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# google-analytics
google_analytics:
repo: https://github.com/hhyxx/yuxuan-hou-x.github.io

###############################################################################
# Social integration
###############################################################################
github_username: hhyxx # put your github username
twitter_username:
linkedin_username:
scholar_authorid:
contact_note: Feel free to reach out by email if you would like to collaborate or chat.

###############################################################################
# Blog
###############################################################################
blog_name: ""
blog_description: ""

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname:

# Optional features
show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true

###############################################################################
# Collections
###############################################################################
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

###############################################################################
# Jekyll settings
###############################################################################

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# plugins
plugins:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Hou
  last_name_equal: Hou*

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

###############################################################################
# Other settings
###############################################################################
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
